import type { DailyDigest } from '../types.js';
import { articleCard } from './templates.js';
import { CSS } from './style.js';

export function buildArchivePage(digest: DailyDigest): string {
  const cards = digest.items.map((item) => articleCard(item)).join('\n    ');

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tech Digest — ${digest.date}</title>
  <style>${CSS}</style>
</head>
<body>
  <header>
    <h1>Tech Digest</h1>
    <p>${digest.date} の厳選 ${digest.items.length} 本</p>
    <nav>
      <a href="../index.html">← 今日のダイジェスト</a>
      <a href="index.html">アーカイブ一覧</a>
    </nav>
  </header>
  <main>
    ${cards}
  </main>
  <footer>
    <p>Generated by Claude Opus 4.6</p>
  </footer>
</body>
</html>`;
}

export function buildArchiveIndex(digests: DailyDigest[]): string {
  const links = digests
    .map(
      (d) =>
        `<a class="archive-link" href="${d.date}.html">${d.date}<span class="count">${d.items.length} 本</span></a>`
    )
    .join('\n    ');

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tech Digest — アーカイブ</title>
  <style>${CSS}</style>
</head>
<body>
  <header>
    <h1>Tech Digest アーカイブ</h1>
    <p>過去 ${digests.length} 日分</p>
    <nav><a href="../index.html">← 今日のダイジェスト</a></nav>
  </header>
  <main>
    ${links}
  </main>
  <footer>
    <p>Generated by Claude Opus 4.6</p>
  </footer>
</body>
</html>`;
}
