import type { DailyDigest } from '../types.js';
import { articleCard, escapeHtml, isValidDate } from './templates.js';
import { CSS } from './style.js';

export function buildArchivePage(digest: DailyDigest): string {
  const cards = digest.items.map((item) => articleCard(item)).join('\n    ');
  const safeDate = escapeHtml(digest.date);
  const safeCount = String(digest.items.length);

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tech Digest — ${safeDate}</title>
  <style>${CSS}</style>
</head>
<body>
  <header>
    <h1>Tech Digest</h1>
    <p>${safeDate} の厳選 ${safeCount} 本</p>
    <nav>
      <a href="../index.html">← 今日のダイジェスト</a>
      <a href="index.html">アーカイブ一覧</a>
    </nav>
  </header>
  <main>
    ${cards}
  </main>
  <footer>
    <p>Generated by Claude Haiku 4.5</p>
  </footer>
</body>
</html>`;
}

export function buildArchiveIndex(digests: DailyDigest[]): string {
  const links = digests
    .filter((d) => isValidDate(d.date))
    .map(
      (d) =>
        `<a class="archive-link" href="${escapeHtml(d.date)}.html">${escapeHtml(d.date)}<span class="count">${String(d.items.length)} 本</span></a>`
    )
    .join('\n    ');

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tech Digest — アーカイブ</title>
  <style>${CSS}</style>
</head>
<body>
  <header>
    <h1>Tech Digest アーカイブ</h1>
    <p>過去 ${String(digests.length)} 日分</p>
    <nav><a href="../index.html">← 今日のダイジェスト</a></nav>
  </header>
  <main>
    ${links}
  </main>
  <footer>
    <p>Generated by Claude Haiku 4.5</p>
  </footer>
</body>
</html>`;
}
