import type { DailyDigest } from '../types.js';
import { articleCard, escapeHtml } from './templates.js';
import {
  CSS,
  FONT_LINKS,
  buildDigestMeter,
  themeToggleHtml,
  themeInitScript,
} from './style.js';

export function buildIndexPage(digest: DailyDigest): string {
  const cards = digest.items.map((item) => articleCard(item)).join('\n    ');
  const safeDate = escapeHtml(digest.date);
  const safeCount = String(digest.items.length);
  const meter = buildDigestMeter(digest.items.length);

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="dark light">
  <title>Tech Digest — ${safeDate}</title>
  ${FONT_LINKS}
  <style>${CSS}</style>
</head>
<body>
  <div class="top-bar">
    <p class="site-title label">Tech Digest</p>
    ${themeToggleHtml()}
  </div>
  <header>
    <div class="header-row">
      <h1 class="display-date">${safeDate}</h1>
      ${meter}
    </div>
    <p class="header-meta">本日の厳選 ${safeCount} 本 — モノクロとタイポで階層化したダイジェスト。</p>
    <nav>
      <a href="archive/index.html">アーカイブ</a>
    </nav>
  </header>
  <main>
    ${cards}
  </main>
  <footer>
    <p>Generated by Claude Haiku 4.5</p>
  </footer>
  ${themeInitScript()}
</body>
</html>`;
}
