import type { DailyDigest } from '../types.js';
import { articleCard, escapeHtml } from './templates.js';
import { CSS, FONT_LINKS } from './style.js';

export function buildIndexPage(digest: DailyDigest): string {
  const cards = digest.items.map((item) => articleCard(item)).join('\n    ');
  const safeDate = escapeHtml(digest.date);
  const safeCount = String(digest.items.length);

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tech Digest — ${safeDate}</title>
  ${FONT_LINKS}
  <style>${CSS}</style>
</head>
<body>
  <header>
    <p class="site-title ndot">Tech Digest</p>
    <h1 class="header-date">${safeDate}</h1>
    <p class="header-meta">本日の厳選 ${safeCount} 本</p>
    <nav>
      <a href="archive/index.html">アーカイブ →</a>
    </nav>
  </header>
  <main>
    ${cards}
  </main>
  <footer>
    <p>Generated by Claude Haiku 4.5</p>
  </footer>
</body>
</html>`;
}
