import type { DailyDigest } from '../types.js';
import { articleCard } from './templates.js';
import { CSS } from './style.js';

export function buildIndexPage(digest: DailyDigest): string {
  const cards = digest.items.map((item) => articleCard(item)).join('\n    ');

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tech Digest — ${digest.date}</title>
  <style>${CSS}</style>
</head>
<body>
  <header>
    <h1>Tech Digest</h1>
    <p>${digest.date} の厳選 ${digest.items.length} 本</p>
    <nav>
      <a href="archive/index.html">過去のアーカイブ →</a>
    </nav>
  </header>
  <main>
    ${cards}
  </main>
  <footer>
    <p>Generated by Claude Opus 4.6</p>
  </footer>
</body>
</html>`;
}
